### ISSUE TITLE
Does it Work

### ISSUE THREAD

**Issue by daulric** [jsdotlua/react-lua#11]
does it work.

**Comment by ghost** [comment]
Yes, it does work. https://discord.gg/pXBE3Asm has a thread if you need to ask any questions. It is used similar to Roact

**Comment by matthargett** [comment]
This is the same code deployed to 150+M users in the Roblox app in 2021, where it doubled the framerate of the app interactions and cut Lua crash rates by 80%. It works :)

**Comment by daulric** [comment]
> This is the same code deployed to 150+M users in the Roblox app in 2021, where it doubled the framerate of the app interactions and cut Lua crash rates by 80%. It works :)

damn

**Comment by daulric** [comment]
> Yes, it does work. https://discord.gg/pXBE3Asm has a thread if you need to ask any questions. It is used similar to Roact

i might try it out
