### ISSUE TITLE
Roact exists

### ISSUE THREAD

**Issue by amol234545** [jsdotlua/react-lua#6]
Why would you make this if there is a **ROBLOX** made version of this?
[github.com/Roblox/roact](github.com/Roblox/roact)

**Comment by amol234545** [comment]
https://github.com/Roblox/roact

**Comment by BrookenRecord** [comment]
React-lua is a 1:1 translation of ReactJS v17. Roblox created it for the universal app, licensed under MIT but not published on GitHub. This repo contains a developer-consumable version of the React translation Roblox made.

Roact is an approximate recreation of ReactJS v16. However, its internal structures are entirely different to upstream React, and it lacks various features and developer tools that React-lua provides (hooks, usage warnings, usable stack traces, error boundary, profiling, and dev tools).

The performance of Roact is somewhat unstable compared to React. Roact isn't necessarily slow (although it is measurably slower than React), but the performance can degrade significantly in several different cases.

Roblox made both. React-lua is the successor to Roact; it just isn't published on GitHub.
